# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 26, 22, 26, 53, 941601, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
